### ISSUE TITLE
How do I access the mysql container locally?

### ISSUE THREAD

**Issue by sterichards** [romaricp/kit-starter-symfony-4-docker#11]
The hostname 'mysql' or 'sf4_mysql' is not valid

➜  web-service git:(master) ✗ ping sf4_mysql
ping: cannot resolve sf4_mysql: Unknown host
➜  web-service git:(master) ✗ ping mysql
ping: cannot resolve mysql: Unknown host

**Comment by GooseBumpsOS** [comment]
> The hostname 'mysql' or 'sf4_mysql' is not valid
> 
> ➜ web-service git:(master) ✗ ping sf4_mysql
> ping: cannot resolve sf4_mysql: Unknown host
> ➜ web-service git:(master) ✗ ping mysql
> ping: cannot resolve mysql: Unknown host


You can use phpmyadmin for this purpose


**docker-compose.yml**
```   
  mysql:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    container_name:mysql
    ports:
      - 3306:3306
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toor
      MYSQL_USER: toor
      MYSQL_PASSWORD: toor

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    links:
      - mysql
```

Just start docker, then go to ```localhost:8080```

![image](https://user-images.githubusercontent.com/32247640/103279949-3247cb80-49e0-11eb-8ec0-a4ce2050e666.png)
